# Generated by Django 3.1.3 on 2020-11-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_m',
            name='slug',
            field=models.SlugField(default='fixme'),
            preserve_default=False,
        ),
    ]
